In [28]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [29]:
df = pd.read_csv('/home/lherrmann/projects/enzyme-design/flip2_Project/data/2_Imin_Reductase_inactive.csv')

In [30]:
df.head()

,aa_seq,Nham_aa,avg_input_count_on,avg_output_count_on
0,HMRDTDVTVLGLGLMGQALAGAFLKVEATTV*NRSEGKVGQLAEQG...,29,34,0
1,IRDTDVTVLGLGLMGQALACAFLKDGHATTVWNRSEGKAGQLAEQG...,3,15,0
2,IRDTDVTVLGLGLMGQALAGAFLKDGHATTAWNRSEGKAGQLAEQG...,2,13,0
3,IRDTDVTVLGLGLMGQALAGAFLKDGHATTVWNRPEGKAGQLAEQG...,4,14,0
4,IRDTDVTVLGLGLMGQALAGAFLKDGHATTVWNRSEGKAGQLAEQG...,125,13,0

In [31]:
df_use = df[~df['aa_seq'].str.contains('*', regex=False)]#, na=False

In [32]:
df_use.count()

aa_seq                 30
Nham_aa                30
avg_input_count_on     30
avg_output_count_on    30
dtype: int64

In [33]:
df_use.head()

,aa_seq,Nham_aa,avg_input_count_on,avg_output_count_on
177,MRDTDVSVLGLGLMGQALAGAFLKDGHATTVLNRSEGKAGQLAEQG...,4,98,0
216,MRDTDVTALGLGLMGQALAGAFLKDGHATTVWNRSEGKAGQLAEQG...,5,62,0
404,MRDTDVTVLGLGLMAQALAGAFLKDGHATTVWNRSEGKAGQLAEQG...,4,19,0
856,MRDTDVTVLGLGLMGQALAGAFLKDGHATTVWNCSEGKAGQLAEQG...,3,37,0
1005,MRDTDVTVLGLGLMGQALAGAFLKDGHATTVWNRSEGKAGHLAEQG...,4,22,0

In [34]:
df_renamed = df_use.rename(columns={
    'aa_seq': 'sequence',
    'Nham_aa': 'target',
    'avg_input_count_on': 'set',
    'avg_output_count_on': 'validation'})

In [37]:
df_renamed.head()

,sequence,target,set,validation
177,MRDTDVSVLGLGLMGQALAGAFLKDGHATTVLNRSEGKAGQLAEQG...,4,98,0
216,MRDTDVTALGLGLMGQALAGAFLKDGHATTVWNRSEGKAGQLAEQG...,5,62,0
404,MRDTDVTVLGLGLMAQALAGAFLKDGHATTVWNRSEGKAGQLAEQG...,4,19,0
856,MRDTDVTVLGLGLMGQALAGAFLKDGHATTVWNCSEGKAGQLAEQG...,3,37,0
1005,MRDTDVTVLGLGLMGQALAGAFLKDGHATTVWNRSEGKAGHLAEQG...,4,22,0

In [ ]:
df_renamed['target'] = -5
df_renamed['set'] = 'train'
df_renamed['validation'] = False

In [40]:
df_renamed.head()

,sequence,target,set,validation
177,MRDTDVSVLGLGLMGQALAGAFLKDGHATTVLNRSEGKAGQLAEQG...,-5,Train,False
216,MRDTDVTALGLGLMGQALAGAFLKDGHATTVWNRSEGKAGQLAEQG...,-5,Train,False
404,MRDTDVTVLGLGLMAQALAGAFLKDGHATTVWNRSEGKAGQLAEQG...,-5,Train,False
856,MRDTDVTVLGLGLMGQALAGAFLKDGHATTVWNCSEGKAGQLAEQG...,-5,Train,False
1005,MRDTDVTVLGLGLMGQALAGAFLKDGHATTVWNRSEGKAGHLAEQG...,-5,Train,False

In [42]:
df_renamed.to_csv('/home/lherrmann/projects/enzyme-design/flip2_Project/2_Imin_Reductase_inactive.csv', index=False)